name: dimens
description: Android-like dimens generator
version: 0.0.2
repository: https://github.com/VasyaFromRussia/flutter-dimens

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.7.0
  _fe_analyzer_shared: ^6.0.0
