name: dimens
description: Android-like dimens generator
version: 0.2.0
repository: https://github.com/VasyaFromRussia/flutter-dimens

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.0.0
